### ISSUE TITLE
Show popup/modal if file sent status 200

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#1]
alert dekaunu paryo hae aryan dai sucess vayepaxi ani loader ni haldinu paryo pending huda phere request

**Comment by itsankitbhusal** [comment]
Can I contribute in this issue ?

**Comment by maheshbasnet089** [comment]
@itsankitbhusal  this issue has been resolved by @A18yan  just few hours ago, there is another features needed to be implemented , this features should make one able to drag and drop their files in the tapshare homescreen. Would you like to contribute in that issue ? @itsankitbhusal

**Comment by if1eight0sty** [comment]
@maheshbasnet089 drag and drop done:)

**Comment by maheshbasnet089** [comment]
😳 I m merging
