### ISSUE TITLE
Make deselect functionality to the selected files 

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#13]
the cancel button for deselecting file  is not working

**Comment by maheshbasnet089** [comment]
@A18yan  we need to fix it asap haha

**Comment by if1eight0sty** [comment]
@maheshbasnet089 copy that🫡

**Comment by if1eight0sty** [comment]
@maheshbasnet089 issue solve vayo voli pull request garxu hai. ani badge t thaa hola LOL
