### ISSUE TITLE
A feature missing.

### ISSUE THREAD

**Issue by sobitkarki1** [maheshbasnet089/tapShare#16]
As, the documentation suggest, there is no way to share to mobile phones using phone numbers as it should be.

**Comment by maheshbasnet089** [comment]
To send files to your phone number, you need to upgrade to a premium user. Please contact us to learn more about upgrading to premium

**Comment by sobitkarki1** [comment]
How much does it cost to upgrade?

Also, there is no upgrade button.

**Comment by maheshbasnet089** [comment]
9.99$ for lifetime

**Comment by maheshbasnet089** [comment]
Message me on my Gmail regarding the upgrade we will do upgrade for you  . Yes currently there is no upgrade button
