### ISSUE TITLE
Add product tour in home page 

### ISSUE THREAD

**Issue by sandeshad100** [maheshbasnet089/tapShare#25]
Can use any package or library

**Comment by maheshbasnet089** [comment]
Yup , will u do It @sandeshad100  or @NGR-NP ?

**Comment by NGR-NP** [comment]
I think @sandeshad100 would be the best fit for adding the product tour on the home page. They have more experience with packages and libraries, which makes them well-equipped for this task.

**Comment by arpan404** [comment]
I can make it

**Comment by maheshbasnet089** [comment]
Okay give it a shot 🥃. Without libraries if u can do that that is awesome
. Libraries are optional if u cannot do it from scratch

**Comment by maheshbasnet089** [comment]
@sandeshad100 any updates regarding this and the about.tapshare.xyz website ?

**Comment by sandeshad100** [comment]
> I can make it

Thats highly appreciated and please have a shot

**Comment by maheshbasnet089** [comment]
We are doing it in about page
