### ISSUE TITLE
copy text

### ISSUE THREAD

**Issue by jay-sambhu** [maheshbasnet089/tapShare#29]
place a copy text  icon while copying the code . And manage the control A command while copying the text because it copy all the text as well as text code of shared file while copying the text

**Comment by maheshbasnet089** [comment]
@sandeshad100 will u do this . I m assigning it to you

**Comment by arpan404** [comment]
This issue is fixed in my latest PR

**Comment by maheshbasnet089** [comment]
Which pull request @arpan404 ?

**Comment by arpan404** [comment]
#47 @maheshbasnet089

**Comment by maheshbasnet089** [comment]
Okay will merge it tonight
