### ISSUE TITLE
Related to sending email

### ISSUE THREAD

**Issue by arpan404** [maheshbasnet089/tapShare#40]
User can click on send email button without entering an email address.
Make sure the email is valid and show the send button only when valid email address is entered.
This will decrease the unnecessary traffic to backend.

**Comment by maheshbasnet089** [comment]
Yes you are true. We can make the field required.

**Comment by arpan404** [comment]
I will make it better by midday

**Comment by maheshbasnet089** [comment]
Okay sir you are going to be highlighted in our cover page . Would u not mind if we add your linkedin photo on it ?

**Comment by arpan404** [comment]
You can

**Comment by arpan404** [comment]
@maheshbasnet089 we need to change the loading animation too.

**Comment by maheshbasnet089** [comment]
Give it a shot we will preview it if it is ok then we will merge it sir

**Comment by maheshbasnet089** [comment]
Closing this issue because it was fixed
