### ISSUE TITLE
add a loader too while fetching data (code/files)

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#50]
loader need while it is still being fetched in the code as well as file page too

**Comment by arpan404** [comment]
Okay ☂︎

**Comment by maheshbasnet089** [comment]
Loader is not being shown @arpan404 why is that or is it my device problem ?

**Comment by maheshbasnet089** [comment]
@arpan404 did u implemented it in viewtext page only ? We need it in all page where there is fetching like tapshare.xyz/1234433

**Comment by maheshbasnet089** [comment]
![Screenshot_2023-07-10-17-52-42-030_com android chrome](https://github.com/maheshbasnet089/tapShare/assets/70196462/d8132832-e586-466b-957c-03e24d5da041)
In these pages of code and file too

**Comment by arpan404** [comment]
Ok

**Comment by arpan404** [comment]
I suggest it to add at this page when it will be redesigned

**Comment by arpan404** [comment]
I will rewrite that page within 2 days

**Comment by arpan404** [comment]
@maheshbasnet089 a suggestion for you, don't import whole React while using builtin hooks like useState, useEffect and so on.
<img width="283" alt="image" src="https://github.com/maheshbasnet089/tapShare/assets/92071427/6b9a52ca-418a-4551-b4e6-0a8fed7f60b8">
Don't do like this, it will hamper the performance and it's not a good code practice of React

**Comment by maheshbasnet089** [comment]
okay @arpan404

**Comment by maheshbasnet089** [comment]
> I will rewrite that page within 2 days

Any updates @arpan404 ?

**Comment by arpan404** [comment]
Currently, I am quite busy on something else. I will do this work when I got free time.

**Comment by maheshbasnet089** [comment]
any updates @arpan404  ?

**Comment by maheshbasnet089** [comment]
@arpan404 updates ?

**Comment by arpan404** [comment]
working on it  currently

**Comment by Suzan-Dev** [comment]
> @maheshbasnet089 a suggestion for you, don't import whole React while using builtin hooks like useState, useEffect and so on. <img alt="image" width="283" src="https://user-images.githubusercontent.com/92071427/252353102-6b9a52ca-418a-4551-b4e6-0a8fed7f60b8.png"> Don't do like this, it will hamper the performance and it's not a good code practice of React

I dont think it hampers the performance.

**Comment by arpan404** [comment]
If the application only uses the useState hook, importing the entire React object will include unnecessary code in your bundle, leading to a larger bundle size. So, to keep your bundle size small and improve performance, it's recommended to import only the specific hook you need.

**Comment by Suzan-Dev** [comment]
> If the application only uses the useState hook, importing the entire React object will include unnecessary code in your bundle, leading to a larger bundle size. So, to keep your bundle size small and improve performance, it's recommended to import only the specific hook you need.

As my understanding, using it like React.useState or using useState after destructuring is similar. In both way, we are using useState only from react. Found this question in stackoverflow too.
https://stackoverflow.com/questions/59025940/should-i-import-usestate-and-useeffect-or-is-it-ok-to-use-react-usestate-and-rea
