### ISSUE TITLE
able to see his recent shared files/codes(history)

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#59]
current userId k cha localStorage ma , tyo id anusar database query garera euta history page ma result dekaunu parney xa 
@NGR-NP .will you help to add this feature or should i assign other?

**Comment by maheshbasnet089** [comment]
@NGR-NP

**Comment by NGR-NP** [comment]
Yea I can do it just suggest me a design yadi Kai sochay ko xeu vhanay?

**Comment by maheshbasnet089** [comment]
it should be simple and user friendly . You can do like that shared code/file ui

**Comment by arpan404** [comment]
I will make it, I got an idea for this

**Comment by arpan404** [comment]
If you wanna make, just make a profile button at top of home page. Redirect the user to /history page and use the components of ViewShared Page of my new PR #60 and modified the text according to need.

**Comment by maheshbasnet089** [comment]
@NGR-NP are u going to do this ? Or should I assign it to @arpan404 ?

**Comment by arpan404** [comment]
I wanna assign this to @maheshbasnet089

**Comment by maheshbasnet089** [comment]
Okay @arpan404 🤠

**Comment by arpan404** [comment]
@maheshbasnet089 I think we should now shift to TypeScript.

**Comment by maheshbasnet089** [comment]
yes we can do that

**Comment by maheshbasnet089** [comment]
@if1eight0sty assigned to you.
