### ISSUE TITLE
404 page is flashed for few seconds user experience 😞

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#61]
@arpan404 can we load 404 page only when link or code not found why it is being flashed when generating link or getting files .can't we load that share text ko jastae fetching data overlay ?

**Comment by arpan404** [comment]
@maheshbasnet089 can you provide me screenshots or video ?

**Comment by arpan404** [comment]
Merge the new PR #62  and it might have not any issue now.

**Comment by maheshbasnet089** [comment]
Uploading Screenrecorder-2023-07-24-14-55-45-706.mp4…

**Comment by maheshbasnet089** [comment]
404 page flashes after link is generated can't we add fetching data like code fetch Garda .404 seems quite odd after link is generated. When code is not found then we can show that

**Comment by maheshbasnet089** [comment]
![Screenshot_2023-07-24-14-59-01-775_com android chrome](https://github.com/maheshbasnet089/tapShare/assets/70196462/cab8bdc5-f27a-441b-a44d-e44af3fd64ef)
 Tyo code at the top right is 213456 static ?

**Comment by maheshbasnet089** [comment]
https://tapshare.xyz/473227 here's is the video of the issue I was taking before 404 flash 📸

**Comment by arpan404** [comment]
check #62

**Comment by maheshbasnet089** [comment]
404 page UI not responsive in laptops

**Comment by maheshbasnet089** [comment]
@arpan404  404 page is still flashing .
