### ISSUE TITLE
 tapShare does not handle file duplicate checking, allowing users to repeatedly send the same file.

### ISSUE THREAD

**Issue by UmeshMehta1** [maheshbasnet089/tapShare#65]

**Comment by brdtheo** [comment]
If each sharing is unique, why would we want to check for duplicates ? I think it is a bad idea since the same file **can** be uploaded from different users (it will generate an unique id anyways)

**Comment by maheshbasnet089** [comment]
Oh I see @brdtheo .Closing this issue
