### ISSUE TITLE
Feature : Send Files to multiple Emails

### ISSUE THREAD

**Issue by maheshbasnet089** [maheshbasnet089/tapShare#78]
User should be available to send files to multiple emails either by manually typing email or selecting the file list containing emails.

**Comment by arpan404** [comment]
Will do it in rewrite.

**Comment by maheshbasnet089** [comment]
@if1eight0sty you are on it ? Working on multiple mails ?

**Comment by if1eight0sty** [comment]
I am working on history, then i will do it🫰
